// 译名偏好，不代表某一赛季的阵容、职务或人员搭配。简称必须先结合上下文消歧。
export const PERSON_NAMES = Object.freeze([
  ['Max Verstappen', 'Verstappen / Max', '维斯塔潘'],
  ['Sergio Perez', 'Sergio Pérez / Perez / Pérez / Checo', '佩雷兹'],
  ['Lewis Hamilton', 'Hamilton / Lewis', '汉密尔顿'],
  ['George Russell', 'Russell / George', '拉塞尔'],
  ['Charles Leclerc', 'Leclerc / Charles', '勒克莱尔'],
  ['Carlos Sainz', 'Sainz / Carlos', '塞恩斯'],
  ['Lando Norris', 'Norris / Lando', '诺里斯'],
  ['Oscar Piastri', 'Piastri / Oscar', '皮亚斯特里'],
  ['Fernando Alonso', 'Alonso / Fernando', '阿隆索'],
  ['Lance Stroll', 'Stroll / Lance', '斯托尔'],
  ['Pierre Gasly', 'Gasly', '加斯利'],
  ['Esteban Ocon', 'Ocon / Esteban', '奥康'],
  ['Alexander Albon', 'Alex Albon / Albon', '阿尔本'],
  ['Yuki Tsunoda', 'Tsunoda / Yuki', '角田裕毅'],
  ['Nico Hulkenberg', 'Nico Hülkenberg / Hulkenberg / Hülkenberg', '霍肯伯格'],
  ['Valtteri Bottas', 'Bottas / Valtteri', '博塔斯'],
  ['Zhou Guanyu', 'Guanyu Zhou / Zhou', '周冠宇'],
  ['Kevin Magnussen', 'Magnussen / Kevin', '马格努森'],
  ['Liam Lawson', 'Lawson / Liam', '劳森'],
  ['Franco Colapinto', 'Colapinto / Franco', '科拉平托'],
  ['Oliver Bearman', 'Ollie Bearman / Bearman / Ollie', '贝尔曼'],
  ['Kimi Antonelli', 'Andrea Kimi Antonelli / Antonelli', '安东内利'],
  ['Jack Doohan', 'Doohan / Jack', '杜汉'],
  ['Gabriel Bortoleto', 'Bortoleto / Gabriel', '博托莱托'],
  ['Christian Horner', 'Horner', '霍纳'],
  ['Toto Wolff', 'Wolff / Toto', '托托'],
  ['Fred Vasseur', 'Frédéric Vasseur / Frederic Vasseur / Vasseur', '瓦塞尔'],
  ['Andrea Stella', 'Stella', '斯特拉'],
  ['James Vowles', 'Vowles', '沃尔斯'],
  ['Mike Krack', 'Krack', '克拉克'],
  ['Ayao Komatsu', 'Komatsu', '小松礼雄'],
  ['Laurent Mekies', 'Mekies', '梅基斯'],
  ['Oliver Oakes', 'Oakes', '奥克斯'],
  ['Mattia Binotto', 'Binotto', '比诺托'],
  ['Gianpiero Lambiase', 'Lambiase / GP', 'GP'],
  ['Peter Bonnington', 'Bonnington / Bono', 'Bono'],
  ['Riccardo Adami', 'Adami', '阿达米'],
  ['Bryan Bozzi', 'Bozzi / Bryan', '布莱恩'],
  ['Will Joseph', 'Joseph', '威尔'],
  ['Tom Stallard', 'Stallard', '汤姆'],
  ['Hugh Bird', 'Bird', '休·伯德'],
  ['Hannah Schmitz', 'Schmitz / Hannah', '汉娜'],
  ['Rosie Wait', 'Rosie', '罗西'],
  ['Adrian Newey', 'Newey', '纽维'],
  ['James Allison', 'Allison', '阿里森'],
  ['Pierre Waché', 'Pierre Wache / Waché / Wache', '瓦谢'],
  ['Dan Fallows', 'Fallows', '法罗斯'],
  ['Enrico Cardile', 'Cardile', '卡迪莱'],
]);

// 只在赛车语义成立时使用；例如 box 的普通名词义不能机械替换成进站。
export const GLOSSARY = Object.freeze({
  'pit stop': '进站', 'box, box': '进站，进站', 'box now': '现在进站', undercut: '提前进站翻越',
  overcut: '晚进站翻越', 'Safety Car': '安全车', 'Virtual Safety Car': '虚拟安全车',
  'track limits': '赛道边界', 'hard tyres': '硬胎', 'medium tyres': '中性胎',
  'soft tyres': '软胎', 'intermediate tyres': '半雨胎', DRS: 'DRS',
  slipstream: '尾流', tow: '尾流（get a tow：吸尾流）', 'dirty air': '脏气流',
  graining: '轮胎颗粒化', blistering: '轮胎起泡', 'lock up': '轮胎锁死',
  'bottoming out': '赛车托底', porpoising: '海豚跳', paddock: '围场', 'pit wall': '维修区指挥台',
  stint: '一段赛程（first stint：第一段赛程；不据此推断已进站几次）',
  degradation: '轮胎衰退', deg: '轮胎衰退', understeer: '转向不足', oversteer: '转向过度',
  'tyre saving': '保胎', 'clean air': '干净气流',
});
